config/routes.rb
Rails.application.routes.draw do
  resources :games
  devise_for :users, :controllers => { :registrations => "registrations" }
  root to: "home#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'
  belongs_to :user, :class_name => 'User', :foreign_key => 'opponent_id'

  def opponent
    return User.find(self.opponent_id)
  end

  def score
    return "#{self.user_score} - #{self.opponent_score}"
  end

  def result
    return self.user_score > self.opponent_score ? "W" : "F"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  scope :opponents, ->(user) { where.not(id: user) }
  scope :games_played, ->(user) { Game.where(user_id: user).count }

  scope :ranking, lambda { User.all.sort_by(&:score).reverse }

  def score
    won_games = Game.where("user_score > opponent_score AND user_id = :id", { id: self.id })
    lost_games = Game.where("user_score < opponent_score AND user_id = :id", { id: self.id })

    return (won_games.count * 100) - (lost_games.count * -50)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def index
        @games = Game.where(user_id: current_user.id)
    end
    
    def new
        @game = Game.new
        @opponents = User.opponents(current_user)
    end

    def create
        @game = Game.new(game_params)
        @game.user_id = current_user.id

        if @game.save
            redirect_to root_path
        else
            render :new
        end
    end

    private
        def game_params
            params.require(:game).permit(:played_at, :user_id, :opponent_id, :user_score, :opponent_score)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.ranking
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1 class="page-header">History</h1>

<table class="table table-striped">
  <thead>
    <th>Date</th>
    <th>Opponent</th>
    <th>Score</th>
    <th>Result</th>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <th><%= game.played_at %></th>
        <td><%= game.opponent.name %></td>
        <td><%= game.score %></td>
        <td><%= game.result %></td>
      <tr>
    <% end %> 
  </tbody>
</table>

app/views/games/new.html.erb
<h1 class="page-header">Log Game</h1>

<%= form_for @game, html: { class: "form-horizontal" } do |f| %>
    <div class="form-group">
        <label for="played_at" class="col-sm-2 control-label">Date Played</label>
        <div class="col-sm-10">
            <%= f.date_select :played_at, {}, { class: "form-control" } %>
        </div>
    </div>
    <div class="form-group">
        <label for="played_at" class="col-sm-2 control-label">Opponent</label>
        <div class="col-sm-10">
            <%= f.collection_select :opponent_id, @opponents, :id, :name, { include_blank: true } , { class: "form-control" } %>
        </div>
    </div>
    <div class="form-group">
        <label for="played_at" class="col-sm-2 control-label">Your Score:</label>
        <div class="col-sm-10">
            <%= f.text_field :user_score, class: "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <label for="played_at" class="col-sm-2 control-label">Their Score:</label>
        <div class="col-sm-10">
            <%= f.text_field :opponent_score, class: "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Save", class: "btn btn-default" %>
            <%= link_to "Cancel", root_path %>
        </div>
    </div>
<% end %>

app/views/home/history.html.erb
<h1 class="page-header">History</h1>

<table class="table table-striped">
  <thead>
    <th>Date</th>
    <th>Opponent</th>
    <th>Score</th>
    <th>Result</th>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <th><%= game.played_at %></th>
        <td><%= game.opponent.name %></td>
        <td><%= game.score %></td>
        <td><%= game.result %></td>
      <tr>
    <% end %> 
  </tbody>
</table>

app/views/home/index.html.erb
<h1 class="page-header">Leaderboard</h1>

<table class="table table-striped">
  <thead>
    <th>Rank</th>
    <th>Name</th>
    <th>Score</th>
    <th>Games Played</th>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
        <tr>
            <th><%= index + 1 %></th>
            <td><%= user.name %></td>
            <td><%= user.score %></td>
            <td><%= User.games_played(user.id) %></td>
        </tr>
    <% end %> 
  </tbody>
</table>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_game_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'History', games_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<%= link_to t(".sign_in", :default => "Sign in"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to t(".sign_up", :default => "Sign up"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
<%= link_to t(".forgot_your_password", :default => "Forgot your password?"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<%= link_to t('.didn_t_receive_confirmation_instructions', :default => "Didn't receive confirmation instructions?"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<%= link_to t('.didn_t_receive_unlock_instructions', :default => "Didn't receive unlock instructions?"), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
  <%= link_to t('.sign_in_with_provider', :provider => provider.to_s.titleize, :default => "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>